"""add account_id to couriers

Revision ID: 4ea651317ac3
Revises: f5bc7c4f4758
Create Date: 2025-06-11 20:24:18.606345

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4ea651317ac3'
down_revision: Union[str, None] = 'f5bc7c4f4758'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('account_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'couriers', 'courier_accounts', ['account_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'couriers', type_='foreignkey')
    op.drop_column('couriers', 'account_id')
    # ### end Alembic commands ###
