"""add position columns

Revision ID: 990d3847584f
Revises: 
Create Date: 2025-05-28 23:35:04.399890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '990d3847584f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('couriers', sa.Column('latitude', sa.Float(), nullable=True))
    op.add_column('couriers', sa.Column('longitude', sa.Float(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('couriers', 'longitude')
    op.drop_column('couriers', 'latitude')
    # ### end Alembic commands ###
