"""update courier and order tables

Revision ID: fe422a0494d5
Revises: 4ea651317ac3
Create Date: 2025-06-30 22:15:31.251403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fe422a0494d5'
down_revision: Union[str, None] = '4ea651317ac3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('orders',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('address', sa.String(), nullable=False),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('courier_id', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(), nullable=True),
    sa.Column('delivered_at', sa.DateTime(), nullable=True),
    sa.Column('recipient_name', sa.String(), nullable=True),
    sa.Column('recipient_phone', sa.String(), nullable=True),
    sa.Column('comment', sa.String(), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['courier_id'], ['couriers.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_orders_id'), 'orders', ['id'], unique=False)
    op.add_column('courier_accounts', sa.Column('is_active', sa.Integer(), nullable=True))
    op.add_column('courier_accounts', sa.Column('last_login', sa.DateTime(), nullable=True))
    op.add_column('couriers', sa.Column('current_order_id', sa.Integer(), nullable=True))
    op.add_column('couriers', sa.Column('last_active', sa.DateTime(), nullable=True))
    op.add_column('couriers', sa.Column('completed_orders_count', sa.Integer(), nullable=True))
    op.alter_column('couriers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.create_unique_constraint(None, 'couriers', ['account_id'])
    op.create_foreign_key(None, 'couriers', 'orders', ['current_order_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'couriers', type_='foreignkey')
    op.drop_constraint(None, 'couriers', type_='unique')
    op.alter_column('couriers', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_column('couriers', 'completed_orders_count')
    op.drop_column('couriers', 'last_active')
    op.drop_column('couriers', 'current_order_id')
    op.drop_column('courier_accounts', 'last_login')
    op.drop_column('courier_accounts', 'is_active')
    op.drop_index(op.f('ix_orders_id'), table_name='orders')
    op.drop_table('orders')
    # ### end Alembic commands ###
